package com.upb.model;
// Generated 13 mai 2023, 08:35:43 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Gestionnaire generated by hbm2java
 */
@Entity
@Table(name = "gestionnaire", catalog = "appg7")
public class Gestionnaire implements java.io.Serializable {

	private Integer idGestionnaire;
	private String nomGestionnaire;
	private String motDePasse;

	public Gestionnaire() {
	}

	public Gestionnaire(String nomGestionnaire, String motDePasse) {
		this.nomGestionnaire = nomGestionnaire;
		this.motDePasse = motDePasse;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_Gestionnaire", unique = true, nullable = false)
	public Integer getIdGestionnaire() {
		return this.idGestionnaire;
	}

	public void setIdGestionnaire(Integer idGestionnaire) {
		this.idGestionnaire = idGestionnaire;
	}

	@Column(name = "Nom_Gestionnaire", nullable = false, length = 128)
	public String getNomGestionnaire() {
		return this.nomGestionnaire;
	}

	public void setNomGestionnaire(String nomGestionnaire) {
		this.nomGestionnaire = nomGestionnaire;
	}

	@Column(name = "mot_de_passe", nullable = false, length = 50)
	public String getMotDePasse() {
		return this.motDePasse;
	}

	public void setMotDePasse(String motDePasse) {
		this.motDePasse = motDePasse;
	}

}
