package com.upb.model;
// Generated 13 mai 2023, 08:35:43 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Membre generated by hbm2java
 */
@Entity
@Table(name = "membre", catalog = "appg7")
public class Membre implements java.io.Serializable {

	private Integer idMembre;
	private String nomMembre;
	private String prenomMembre;
	private String adresseMembre;
	private String telephone;
	private String profession;
	private String email;

	public Membre() {
	}

	public Membre(String nomMembre, String prenomMembre, String adresseMembre, String telephone, String profession,
			String email) {
		this.nomMembre = nomMembre;
		this.prenomMembre = prenomMembre;
		this.adresseMembre = adresseMembre;
		this.telephone = telephone;
		this.profession = profession;
		this.email = email;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_Membre", unique = true, nullable = false)
	public Integer getIdMembre() {
		return this.idMembre;
	}

	public void setIdMembre(Integer idMembre) {
		this.idMembre = idMembre;
	}

	@Column(name = "Nom_membre", nullable = false, length = 50)
	public String getNomMembre() {
		return this.nomMembre;
	}

	public void setNomMembre(String nomMembre) {
		this.nomMembre = nomMembre;
	}

	@Column(name = "Prenom_Membre", nullable = false, length = 120)
	public String getPrenomMembre() {
		return this.prenomMembre;
	}

	public void setPrenomMembre(String prenomMembre) {
		this.prenomMembre = prenomMembre;
	}

	@Column(name = "Adresse_Membre", nullable = false, length = 65535)
	public String getAdresseMembre() {
		return this.adresseMembre;
	}

	public void setAdresseMembre(String adresseMembre) {
		this.adresseMembre = adresseMembre;
	}

	@Column(name = "Telephone", nullable = false, length = 50)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "Profession", nullable = false, length = 65535)
	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	@Column(name = "Email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
