package com.upb.model;
// Generated 13 mai 2023, 08:35:43 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Scores generated by hbm2java
 */
@Entity
@Table(name = "scores", catalog = "appg7")
public class Scores implements java.io.Serializable {

	private Integer idScore;
	private String nomGagnant;
	private String nomPerdant;
	private int nombreJeuSet1Gagnant;
	private int nombreJeuSet1Perdant;
	private int nombreSetGagnant;
	private int nombreSetPerdant;
	private int nombreJeuSet2Gagnant;
	private int nombreJeuSet2Perdant;
	private int nombreJeuSet3Gagnant;
	private int nombreJeuSet3Perdant;
	private int nombreJeuSet4Gagnant;
	private int nombreJeuSet4Perdant;

	public Scores() {
	}

	public Scores(String nomGagnant, String nomPerdant, int nombreJeuSet1Gagnant, int nombreJeuSet1Perdant,
			int nombreSetGagnant, int nombreSetPerdant, int nombreJeuSet2Gagnant, int nombreJeuSet2Perdant,
			int nombreJeuSet3Gagnant, int nombreJeuSet3Perdant, int nombreJeuSet4Gagnant, int nombreJeuSet4Perdant) {
		this.nomGagnant = nomGagnant;
		this.nomPerdant = nomPerdant;
		this.nombreJeuSet1Gagnant = nombreJeuSet1Gagnant;
		this.nombreJeuSet1Perdant = nombreJeuSet1Perdant;
		this.nombreSetGagnant = nombreSetGagnant;
		this.nombreSetPerdant = nombreSetPerdant;
		this.nombreJeuSet2Gagnant = nombreJeuSet2Gagnant;
		this.nombreJeuSet2Perdant = nombreJeuSet2Perdant;
		this.nombreJeuSet3Gagnant = nombreJeuSet3Gagnant;
		this.nombreJeuSet3Perdant = nombreJeuSet3Perdant;
		this.nombreJeuSet4Gagnant = nombreJeuSet4Gagnant;
		this.nombreJeuSet4Perdant = nombreJeuSet4Perdant;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_Score", unique = true, nullable = false)
	public Integer getIdScore() {
		return this.idScore;
	}

	public void setIdScore(Integer idScore) {
		this.idScore = idScore;
	}

	@Column(name = "Nom_gagnant", nullable = false, length = 120)
	public String getNomGagnant() {
		return this.nomGagnant;
	}

	public void setNomGagnant(String nomGagnant) {
		this.nomGagnant = nomGagnant;
	}

	@Column(name = "Nom_perdant", nullable = false, length = 120)
	public String getNomPerdant() {
		return this.nomPerdant;
	}

	public void setNomPerdant(String nomPerdant) {
		this.nomPerdant = nomPerdant;
	}

	@Column(name = "Nombre_Jeu_Set1_Gagnant", nullable = false)
	public int getNombreJeuSet1Gagnant() {
		return this.nombreJeuSet1Gagnant;
	}

	public void setNombreJeuSet1Gagnant(int nombreJeuSet1Gagnant) {
		this.nombreJeuSet1Gagnant = nombreJeuSet1Gagnant;
	}

	@Column(name = "Nombre_Jeu_Set1_Perdant", nullable = false)
	public int getNombreJeuSet1Perdant() {
		return this.nombreJeuSet1Perdant;
	}

	public void setNombreJeuSet1Perdant(int nombreJeuSet1Perdant) {
		this.nombreJeuSet1Perdant = nombreJeuSet1Perdant;
	}

	@Column(name = "Nombre_set_gagnant", nullable = false)
	public int getNombreSetGagnant() {
		return this.nombreSetGagnant;
	}

	public void setNombreSetGagnant(int nombreSetGagnant) {
		this.nombreSetGagnant = nombreSetGagnant;
	}

	@Column(name = "Nombre_set_perdant", nullable = false)
	public int getNombreSetPerdant() {
		return this.nombreSetPerdant;
	}

	public void setNombreSetPerdant(int nombreSetPerdant) {
		this.nombreSetPerdant = nombreSetPerdant;
	}

	@Column(name = "Nombre_Jeu_Set2_Gagnant", nullable = false)
	public int getNombreJeuSet2Gagnant() {
		return this.nombreJeuSet2Gagnant;
	}

	public void setNombreJeuSet2Gagnant(int nombreJeuSet2Gagnant) {
		this.nombreJeuSet2Gagnant = nombreJeuSet2Gagnant;
	}

	@Column(name = "Nombre_Jeu_Set2_Perdant", nullable = false)
	public int getNombreJeuSet2Perdant() {
		return this.nombreJeuSet2Perdant;
	}

	public void setNombreJeuSet2Perdant(int nombreJeuSet2Perdant) {
		this.nombreJeuSet2Perdant = nombreJeuSet2Perdant;
	}

	@Column(name = "Nombre_Jeu_Set3_Gagnant", nullable = false)
	public int getNombreJeuSet3Gagnant() {
		return this.nombreJeuSet3Gagnant;
	}

	public void setNombreJeuSet3Gagnant(int nombreJeuSet3Gagnant) {
		this.nombreJeuSet3Gagnant = nombreJeuSet3Gagnant;
	}

	@Column(name = "Nombre_Jeu_Set3_Perdant", nullable = false)
	public int getNombreJeuSet3Perdant() {
		return this.nombreJeuSet3Perdant;
	}

	public void setNombreJeuSet3Perdant(int nombreJeuSet3Perdant) {
		this.nombreJeuSet3Perdant = nombreJeuSet3Perdant;
	}

	@Column(name = "Nombre_Jeu_Set4_Gagnant", nullable = false)
	public int getNombreJeuSet4Gagnant() {
		return this.nombreJeuSet4Gagnant;
	}

	public void setNombreJeuSet4Gagnant(int nombreJeuSet4Gagnant) {
		this.nombreJeuSet4Gagnant = nombreJeuSet4Gagnant;
	}

	@Column(name = "Nombre_Jeu_Set4_Perdant", nullable = false)
	public int getNombreJeuSet4Perdant() {
		return this.nombreJeuSet4Perdant;
	}

	public void setNombreJeuSet4Perdant(int nombreJeuSet4Perdant) {
		this.nombreJeuSet4Perdant = nombreJeuSet4Perdant;
	}

}
